import{a as f,S as A,i as l}from"./assets/vendor-CZ-iLBCt.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();const g="51390103-e5f94b12a87f57c9fbe51ad97";function h(r){return f("https://pixabay.com/api/",{params:{key:g,q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data.hits).catch(t=>{throw t})}const d=document.querySelector(".gallery"),u=document.querySelector(".loader");function y(r){const t=r.map(({webformatURL:i,tags:o,largeImageURL:e,likes:s,views:a,comments:m,downloads:p})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${e}">
                <img src="${i}" alt="${o}">
                <div class="image-stats">
                    <p class="img-stat-text"><span class="img-stat-header">Likes</span> ${s}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Views</span> ${a}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Comments</span> ${m}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Downloads</span> ${p}</p>
                </div>
            </a>
        </li>
    `).join("");d.insertAdjacentHTML("beforeend",t),L.refresh()}let L=new A(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function E(){d.innerHTML=""}function w(){u.classList.remove("hidden")}function S(){u.classList.add("hidden")}const P="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAhUExURfn5+/v7+/n5+0dwTPr6/Pn5+vn5+/r6+vT0+vT09Pr6+69tr8QAAAAKdFJOU4B/fwCfoK8wMDCbJE/NAAAAn0lEQVQY00XQIY7DMBCG0ZHMzEJLzYyiPEW7vLfoEULLSvcirrWKVJ9ywTYNfPrI/BPIY4zREMz7NE3TlgjyFdZGmH+BWxLvwNrEEbilyFdfcLe22Hkk5hdbPFkauXCJJ2qauwNLy+UDtTuR24m51/RBLks7MHdq4hI7j8LyYot69Q0/1h7LeWgJ9ZjQhSPdivBOaydY/h9SCNQxxuj4A4bdSawyd2feAAAAAElFTkSuQmCC",b=document.querySelector(".form"),c=document.querySelector('input[name="search-text"]');b.addEventListener("submit",r=>{if(r.preventDefault(),E(),!c.value){n("Empty input. Please type images you want ot find!");return}w(),h(c.value.trim()).then(t=>{if(!t.length){n("Sorry, there are no images matching your search query. Please try again!");return}y(t),l.success({message:"This is what was found!",position:"topLeft",messageSize:16,messageLineHeight:24,closeOnEscape:!0,closeOnClick:!0})}).catch(t=>{n("Oops... Something went wrong. Please, try again!")}).finally(()=>{S()})});function n(r){l.error({message:r,messageColor:"#fafafb",messageSize:16,messageLineHeight:24,position:"topRight",displayMode:"replace",closeOnEscape:!0,closeOnClick:!0,iconUrl:P,theme:"dark",backgroundColor:"#ef4040",maxWidth:432})}
//# sourceMappingURL=index.js.map
