import{a as B,S as C,i as d}from"./assets/vendor-Dlc6jZjm.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const P="51390103-e5f94b12a87f57c9fbe51ad97",h=15;async function p(e,r){try{return(await B("https://pixabay.com/api/",{params:{key:P,q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:h}})).data}catch(o){throw o}}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");function y(e){const r=e.map(({webformatURL:o,tags:i,largeImageURL:t,likes:s,views:n,comments:S,downloads:v})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${t}">
                <img src="${o}" alt="${i}">
                <div class="image-stats">
                    <p class="img-stat-text"><span class="img-stat-header">Likes</span> ${s}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Views</span> ${n}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Comments</span> ${S}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Downloads</span> ${v}</p>
                </div>
            </a>
        </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),O.refresh()}let O=new C(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function k(){f.innerHTML=""}function A(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function w(){u.classList.remove("hidden")}function m(){u.classList.add("hidden")}const x="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAhUExURfn5+/v7+/n5+0dwTPr6/Pn5+vn5+/r6+vT0+vT09Pr6+69tr8QAAAAKdFJOU4B/fwCfoK8wMDCbJE/NAAAAn0lEQVQY00XQIY7DMBCG0ZHMzEJLzYyiPEW7vLfoEULLSvcirrWKVJ9ywTYNfPrI/BPIY4zREMz7NE3TlgjyFdZGmH+BWxLvwNrEEbilyFdfcLe22Hkk5hdbPFkauXCJJ2qauwNLy+UDtTuR24m51/RBLks7MHdq4hI7j8LyYot69Q0/1h7LeWgJ9ZjQhSPdivBOaydY/h9SCNQxxuj4A4bdSawyd2feAAAAAElFTkSuQmCC",M=document.querySelector(".form"),l=document.querySelector("input[name='search-text']");let b="",c=1,E=0;async function T(){if(k(),!l.value){a("Empty input. Please type images you want ot find!");return}A();try{const e=await p(l.value.trim(),c);if(!e.hits.length){a("Sorry, there are no images matching your search query. Please try again!");return}b=l.value.trim(),E=Math.ceil(e.totalHits/h),y(e.hits),d.success({message:"This is what was found!",position:"topLeft",messageSize:16,messageLineHeight:24,closeOnEscape:!0,closeOnClick:!0})}catch(e){console.log(e),a("Oops... Something went wrong. Please, try again!")}finally{L(),w()}}async function q(){m(),c+=1,A();try{const e=await p(b,c);y(e.hits);const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch(e){Q(e)}finally{if(L(),c===E){d.warning({message:"We're sorry, but you've reached the end of search results.",messageColor:"#0c0c0c",messageSize:16,messageLineHeight:24,position:"bottomCenter",closeOnEscape:!0,closeOnClick:!0}),m();return}w()}}function a(e){d.error({message:e,messageColor:"#fafafb",messageSize:16,messageLineHeight:24,position:"topRight",displayMode:"replace",closeOnEscape:!0,closeOnClick:!0,iconUrl:x,theme:"dark",backgroundColor:"#ef4040",maxWidth:432})}function Q(e){const r=e.response?.status;switch(r){case 429:a("Don't push the horses! Too many requests.");break;case 401:a("Access denied.");break;case 404:a("Resource not found");break;default:a(`Error ${r||"unknown"}`)}}M.addEventListener("submit",e=>{e.preventDefault(),T()});u.addEventListener("click",q);
//# sourceMappingURL=index.js.map
