import{a as B,S as C,i as m}from"./assets/vendor-Dlc6jZjm.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const P="51390103-e5f94b12a87f57c9fbe51ad97",h=15;async function p(e,r){try{return(await B("https://pixabay.com/api/",{params:{key:P,q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:h}})).data}catch(o){throw o}}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");function A(e){const r=e.map(({webformatURL:o,tags:c,largeImageURL:t,likes:s,views:i,comments:S,downloads:v})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${t}">
                <img src="${o}" alt="${c}">
                <div class="image-stats">
                    <p class="img-stat-text"><span class="img-stat-header">Likes</span> ${s}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Views</span> ${i}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Comments</span> ${S}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Downloads</span> ${v}</p>
                </div>
            </a>
        </li>
    `).join("");g.insertAdjacentHTML("beforeend",r),O.refresh()}let O=new C(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function k(){g.innerHTML=""}function L(){y.classList.remove("hidden")}function w(){y.classList.add("hidden")}function b(){f.classList.remove("hidden")}function d(){f.classList.add("hidden")}const x="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAhUExURfn5+/v7+/n5+0dwTPr6/Pn5+vn5+/r6+vT0+vT09Pr6+69tr8QAAAAKdFJOU4B/fwCfoK8wMDCbJE/NAAAAn0lEQVQY00XQIY7DMBCG0ZHMzEJLzYyiPEW7vLfoEULLSvcirrWKVJ9ywTYNfPrI/BPIY4zREMz7NE3TlgjyFdZGmH+BWxLvwNrEEbilyFdfcLe22Hkk5hdbPFkauXCJJ2qauwNLy+UDtTuR24m51/RBLks7MHdq4hI7j8LyYot69Q0/1h7LeWgJ9ZjQhSPdivBOaydY/h9SCNQxxuj4A4bdSawyd2feAAAAAElFTkSuQmCC",M=document.querySelector(".form"),l=document.querySelector("input[name='search-text']");let E="",n=1,u=0;async function T(){if(n=1,k(),d(),!l.value.trim()){a("Empty input. Please type images you want ot find!");return}L();try{const e=await p(l.value.trim(),n);if(!e.hits.length){a("Sorry, there are no images matching your search query. Please try again!");return}if(E=l.value.trim(),u=Math.ceil(e.totalHits/h),A(e.hits),m.success({message:"This is what was found!",position:"topLeft",messageSize:16,messageLineHeight:24,closeOnEscape:!0,closeOnClick:!0}),n===u)return;b()}catch(e){console.log(e),a("Oops... Something went wrong. Please, try again!")}finally{w()}}async function q(){d(),n+=1,L();try{const e=await p(E,n);A(e.hits);const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch(e){Q(e)}finally{if(w(),n===u){m.warning({message:"We're sorry, but you've reached the end of search results.",messageColor:"#0c0c0c",messageSize:16,messageLineHeight:24,position:"bottomCenter",closeOnEscape:!0,closeOnClick:!0}),d();return}b()}}function a(e){m.error({message:e,messageColor:"#fafafb",messageSize:16,messageLineHeight:24,position:"topRight",displayMode:"replace",closeOnEscape:!0,closeOnClick:!0,iconUrl:x,theme:"dark",backgroundColor:"#ef4040",maxWidth:432})}function Q(e){const r=e.response?.status;switch(r){case 429:a("Don't push the horses! Too many requests.");break;case 401:a("Access denied.");break;case 404:a("Resource not found");break;default:a(`Error ${r||"unknown"}`)}}M.addEventListener("submit",e=>{e.preventDefault(),T()});f.addEventListener("click",q);
//# sourceMappingURL=index.js.map
